//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRQ.Avalicacao.EderSESanto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidato
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public Nullable<int> Idade { get; set; }
        public string NomePai { get; set; }
        public string NomeMae { get; set; }
        public string RG { get; set; }
    }
}
